### PR TITLE
make llvm-config --version patch version optional, defaulted to 0

### PR DESCRIPTION
**Pull request by x37v**
ubuntu 14.04.5 llvm-config returns "3.4"

*3.4* becomes *3.4.0* to be passed to `Version`

### CODE REVIEW

**Comment by tari** [comment]
I'm hesitant to make this change just because LLVM 3.4 is so old. The earliest version I'm officially trying to support is 3.6.0, but if you really need 3.4 I'm willing to consider it.

Based on the LLVM release history, 3.4 was the last version that didn't include a patch revision- 3.4.1 was the first that did, and all subsequent releases have (though I don't know if 3.4.1 identifies itself as 3.4).

**Comment by x37v** [comment]
Before the changes the output of `cargo build` is this on my machine:

       Compiling llvm-sys v50.0.1 (file:///home/alex/projects/llvm-sys.rs)
    error: failed to run custom build command for `llvm-sys v50.0.1 (file:///home/alex/projects/llvm-sys.rs)`
    process didn't exit successfully: `/home/alex/projects/llvm-sys.rs/target/debug/build/llvm-sys-356b87d0e9cd5d85/build-script-build` (exit code: 101)
    --- stderr
    thread 'main' panicked at 'Could not determine LLVM version from llvm-config.', /checkout/src/libcore/option.rs:891:4


Afterwards it is much more helpful, indicating a version that is not supported:

       Compiling llvm-sys v50.0.1 (file:///home/alex/projects/llvm-sys.rs)
    error: failed to run custom build command for `llvm-sys v50.0.1 (file:///home/alex/projects/llvm-sys.rs)`
    process didn't exit successfully: `/home/alex/projects/llvm-sys.rs/target/debug/build/llvm-sys-356b87d0e9cd5d85/build-script-build` (exit code: 101)
    --- stdout
    Found LLVM version 3.4.0 on PATH, but need 5.0.1.
    Didn't find usable system-wide LLVM.
    LLVM_SYS_50_PREFIX not set, not using precompiled binaries
    LLVM_SYS_50_AUTOBUILD not set, will not automatically compile LLVM
    
    --- stderr
    thread 'main' panicked at 'Could not find a compatible version of LLVM', build.rs:77:8

Even if you're not supporting anything less than 3.6 and at that point if the version has a patch number I figure it would be better if the parser could indicate the issue more gracefully than just fail with a message that indicates the real problem and not some issue with parsing the version.

The `Version` parser should also probably be updated to be able to compare *3.4* with *5.6.0* but the code as is fails before even trying *3.4* as it requires the patch number in the regex.

**Comment by tari** [comment]
Fair enough; applied. Thanks for the PR!

**Comment by x37v** [comment]
happy to help!

**Pull request merged**
